package requests

type Header struct {
	DeliveryDocument                int      `json:"DeliveryDocument"`
	Buyer                           *int     `json:"Buyer"`
	Seller                          *int     `json:"Seller"`
	ReferenceDocument               *int     `json:"ReferenceDocument"`
	ReferenceDocumentItem           *int     `json:"ReferenceDocumentItem"`
	OrderID                         *int     `json:"OrderID"`
	OrderItem                       *int     `json:"OrderItem"`
	ContractType                    *string  `json:"ContractType"`
	OrderValidityStartDate          *string  `json:"OrderVaridityStartDate"`
	OrderValidityEndDate            *string  `json:"OrderValidityEndDate"`
	IssuingPlantTimeZone            *string  `json:"IssuingPlantTimeZone"`
	ReceivingPlantTimeZone          *string  `json:"ReceivingPlantTimeZone"`
	DocumentDate                    *string  `json:"DocumentDate"`
	PlannedGoodsIssueDate           *string  `json:"PlannedGoodsIssueDate"`
	PlannedGoodsIssueTime           *string  `json:"PlannedGoodsIssueTime"`
	PlannedGoodsReceiptDate         *string  `json:"PlannedGoodsReceiptDate"`
	PlannedGoodsReceiptTime         *string  `json:"PlannedGoodsReceiptTime"`
	InvoiceDocumentDate             *string  `json:"InvoiceDocumentDate"`
	HeaderCompleteDeliveryIsDefined *bool    `json:"CompleteDeliveryIsDefined"`
	HeaderDeliveryStatus            *string  `json:"OverallDeliveryStatus"`
	CreationDate                    *string  `json:"CreationDate"`
	CreationTime                    *string  `json:"CreationTime"`
	HeaderDeliveryBlockStatus       *bool    `json:"HeaderDeliveryBlockStatus"`
	HeaderIssuingBlockStatus        *bool    `json:"HeaderIssuingBlockStatus"`
	HeaderReceivingBlockStatus      *bool    `json:"HeaderReceivingBlockStatus"`
	GoodsIssueOrReceiptSlipNumber   *string  `json:"GoodsIssueOrReceiptSlipNumber"`
	HeaderBillingStatus             *string  `json:"HeaderBillingStatus"`
	HeaderBillingConfStatus         *string  `json:"HeaderBillingConfStatus"`
	HeaderBillingBlockStatus        *bool    `json:"HeaderBillingBlockStatus"`
	HeaderGrossWeight               *float32 `json:"HeaderGrossWeight"`
	HeaderNetWeight                 *float32 `json:"HeaderNetWeight"`
	HeaderWeightUnit                *string  `json:"HeaderWeightUnit"`
	Incoterms                       *string  `json:"Incoterms"`
	BillFromParty                   *int     `json:"BillFromParty"`
	BillToParty                     *int     `json:"BillToParty"`
	BillFromCountry                 *string  `json:"BillFromCountry"`
	BillToCountry                   *string  `json:"BillToCountry"`
	Payer                           *int     `json:"Payer"`
	Payee                           *int     `json:"Payee"`
	IsExportImportDelivery          *bool    `json:"IsExportImportDelivery"`
	LastChangeDate                  *string  `json:"LastChangeDate"`
	IssuingPlantBusinessPartner     *string  `json:"IssuingPlantBusinessPartner"`
	IssuingPlant                    *string  `json:"IssuingPlant"`
	ReceivingPlantBusinessPartner   *string  `json:"ReceivingPlantBusinessPartner"`
	ReceivingPlant                  *string  `json:"ReceivingPlant"`
	DeliverToParty                  *int     `json:"DeliverToParty"`
	DeliverFromParty                *int     `json:"DeliverFromParty"`
	TransactionCurrency             *string  `json:"TransactionCurrency"`
	StockIsFullyConfirmed           *int     `json:"StockIsFullyConfirmed"`
}
